TERMINAL_APP_URI = 'ui://gate/terminal.html'

TERMINAL_APP_HTML = r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width">
<style>
:root{color-scheme:dark;font:13px ui-monospace,SFMono-Regular,Consolas,monospace}*{box-sizing:border-box}body{margin:0;background:#020804;color:#b8c7bd}.app{border:1px solid #184529;border-radius:10px;overflow:hidden}.head,.stats,.actions{display:flex;gap:12px;align-items:center;padding:10px 12px;background:#06110a}.head{justify-content:space-between;color:#5cff87}.stats{color:#829489;border-block:1px solid #132d1c}.queue{max-height:280px;overflow:auto}.job{display:grid;grid-template-columns:12px 1fr auto;gap:8px;padding:9px 12px;border-bottom:1px solid #102519;cursor:pointer}.job:hover{background:#07170d}.dot{color:#5cff87}.failed,.stderr{color:#ff796f}.waiting,.system{color:#829489}.last{grid-column:2/4;color:#829489;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.terminal{display:none;background:#020804;color:#5cff87;padding:12px;max-height:360px;overflow:auto;white-space:pre-wrap;text-shadow:0 0 8px rgba(92,255,135,.25)}.terminal.open{display:block}.line.stdout{color:#5cff87}.line.stderr{color:#ff9a6f}.line.system{color:#66766b}.actions{border-top:1px solid #132d1c}button{background:#102519;color:#c8d7cd;border:1px solid #245d38;border-radius:5px;padding:6px 10px}.recovery{display:none;padding:14px;background:#2a1c08;color:#ffd38a}.recovery.open{display:block}.empty{padding:20px;text-align:center;color:#66766b}
</style></head><body><main class="app"><header class="head"><b>Gate Live Queue</b><span id="status">● Waiting</span></header><section id="recovery" class="recovery">Pending tasks recovered after restart. <button data-recovery="resume">Relancer</button> <button data-recovery="clear">Vider</button></section><section id="stats" class="stats"></section><section id="queue" class="queue"></section><section id="terminal" class="terminal"></section><footer class="actions"><button id="stop">Stop</button><button id="copy">Copy</button><button id="logs">Open logs</button></footer></main>
<script>
const terminal=document.querySelector('#terminal'),queue=document.querySelector('#queue'),stats=document.querySelector('#stats'),recovery=document.querySelector('#recovery');let selected=null,cursor=0,lines=[],stick=true,timer,detailDone=false;
const data=r=>r?.structuredContent||r?.content?.find?.(x=>x.type==='text')?.text&&JSON.parse(r.content.find(x=>x.type==='text').text)||r;
async function call(name,args={}){return data(await window.openai.callTool(name,args))}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(s){stats.textContent=`Workers ${s.workers.active}/${s.workers.limit} · Queued ${s.queued} · Failed ${s.failed} · Completed ${s.completed}`;recovery.classList.toggle('open',s.recovery_required);queue.innerHTML=s.commands.length?s.commands.slice(0,8).map(j=>`<article class="job" data-id="${j.execution_id}"><span class="dot ${j.status}">●</span><b>${esc(j.command)}</b><span>${Math.round(j.duration_ms/1000)}s</span><span class="last ${j.last_stream||''}">${esc(j.last_line||j.status)}</span></article>`).join(''):'<div class="empty">No commands</div>';document.querySelector('#status').textContent=s.workers.active?'● Running':'● Waiting'}
async function poll(){try{render(await call('get_queue_state'));if(selected&&!detailDone)await detail()}finally{timer=setTimeout(poll,document.hidden?2000:750)}}
async function detail(){const s=await call('get_command_state',{execution_id:selected,after_cursor:cursor,limit:200});for(const l of s.lines){if(l.replace&&lines.length)lines.pop();lines.push(l);cursor=l.cursor}terminal.innerHTML=lines.map(l=>`<div class="line ${l.stream}">${esc(l.text)}</div>`).join('');if(stick)terminal.scrollTop=terminal.scrollHeight;if(['success','failed','cancelled','timeout','interrupted'].includes(s.status)&&!s.has_more){detailDone=true;document.querySelector('#status').textContent=`● ${s.status}`}}
queue.onclick=e=>{const row=e.target.closest('[data-id]');if(!row)return;selected=row.dataset.id;cursor=0;lines=[];detailDone=false;terminal.classList.add('open');detail()};terminal.onscroll=()=>stick=terminal.scrollTop+terminal.clientHeight>=terminal.scrollHeight-8;
document.querySelector('#stop').onclick=()=>selected&&call('stop_command',{execution_id:selected});document.querySelector('#copy').onclick=()=>navigator.clipboard.writeText(lines.map(x=>x.text).join('\n'));document.querySelector('#logs').onclick=async()=>{if(!selected)return;let offset=0,chunks=[],more=true;while(more){const out=await call('get_command_log',{execution_id:selected,offset,limit_bytes:262144});const raw=atob(out.content_base64),bytes=Uint8Array.from(raw,c=>c.charCodeAt(0));chunks.push(bytes);offset=out.offset;more=out.has_more}const blob=new Blob(chunks,{type:'text/plain'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${selected}.log`;a.click();URL.revokeObjectURL(a.href)};recovery.onclick=e=>e.target.dataset.recovery&&call('resolve_command_recovery',{action:e.target.dataset.recovery});document.addEventListener('visibilitychange',()=>{clearTimeout(timer);poll()});poll();
</script></body></html>'''
